FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache git build-base && \
    go install github.com/air-verse/air@latest && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest && \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Air will watch files and rebuild
CMD ["air", "-c", ".air.toml"]
